# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 03:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debtpages_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='burrower',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='debts_burrowed', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debt',
            name='lender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='debts_lended', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
